### ISSUE TITLE
SystemMessage Example is not working on 0.4.1

### ISSUE THREAD

**Issue by youzhou-youpi** [logspace-ai/langflow_examples#14]
After building, the HumanMessagePromptTemplate block shows below error:

Error building node HumanMessagePromptTemplate: 'HumanMessagePromptTemplate' object has no attribute 'partial'
